package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* mercredi 1 décembre 2021 09 h 11 WAT
*/

public interface IBanqueRemoteOperations 
{
  double conv (double mt);
  void creeCompte (corbaBanque.Compte c);
  void verser (int code, double mt);
  void retirer (int code, double mt);
  corbaBanque.Compte getCompte (int code);
  corbaBanque.Compte[] getComptes ();
} // interface IBanqueRemoteOperations
